### ISSUE TITLE
특정 상황에 글 작성 시 오류 발생

### ISSUE THREAD

**Issue by taesikyoon** [QBChaining/QBChaining-BE#220]
![image](https://user-images.githubusercontent.com/90764424/192084575-1919eff2-da29-4a4b-8b5a-b812eef71b90.png)

**Comment by taesikyoon** [comment]
이모지가 들어가면 오류를 내는것으로 확인
![image](https://user-images.githubusercontent.com/90764424/192087540-bcbf120d-b672-4fbe-ab8a-d13d071525dd.png)
   
위 이미지 변경사항 반영 후 이모지가 잘 들어가는 것 으로 확인했음

**Comment by kpzzy** [comment]
모든 모델 utf8mb4,  utf8mb4_unicode_ci로 바꿔야됨

**Comment by taesikyoon** [comment]
varchar와 text의 차이가 무엇인지 알아보는게 좋은것 같음 
현재 qna는 text로 데이터타입을 지정했고 post는 varchar로 지정되어있음
text의 선택 이유는 데이터의 길이를 예측할 수 없을거 같아서 사용했으나 검색부분에서는 성능저하가 있다고 알고있음

**Comment by taesikyoon** [comment]
같은 기준에서 무슨 차이가 나는 지 알 수 없음 
검색 시 , 또는 데이터 조회 시 margon에서 주는 정보로 확인하는 데이터는 큰 차이가 없는것으로 보이며
실제로 STRING으로 sequelize 데이터 타입을 변경 시 확인해보면 MEDIUMTEXT로 변경되어있음을 확인
