### ISSUE TITLE
github action 으로 CI/CD를 해보자

### ISSUE THREAD

**Issue by kpzzy** [QBChaining/QBChaining-BE#95]
# 튜토리얼

## 읽고 들어가기
- Workflow
자동화된 전체 프로세스. 하나 이상의 Job으로 구성되고, Event에 의해 예약되거나 트리거될 수 있는 자동화된 절차를 말한다.
Workflow 파일은 YAML으로 작성되고, Github Repository의 .github/workflows 폴더 아래에 저장된다. Github에게 YAML 파일로 정의한 자동화 동작을 전달하면, Github Actions는 해당 파일을 기반으로 그대로 실행시킨다.

- Event
Workflow를 트리거(실행)하는 특정 활동이나 규칙. 예를 들어, 누군가가 커밋을 리포지토리에 푸시하거나 풀 요청이 생성 될 때 GitHub에서 활동이 시작될 수 있다.

- Job
Job은 여러 Step으로 구성되고, 단일 가상 환경에서 실행된다. 다른 Job에 의존 관계를 가질 수도 있고, 독립적으로 병렬로 실행될 수도 있다.

- Step
Job 안에서 순차적으로 실행되는 프로세스 단위. step에서 명령을 내리거나, action을 실행할 수 있다.

- Action
job을 구성하기 위한 step들의 조합으로 구성된 독립적인 명령. workflow의 가장 작은 빌드 단위이다. workflow에서 action을 사용하기 위해서는 action이 step을 포함해야 한다. action을 구성하기 위해서 레포지토리와 상호작용하는 커스텀 코드를 만들 수도 있다. 사용자가 직접 커스터마이징하거나, 마켓플레이스에 있는 action을 가져다 사용할 수도 있다. (더 자세한 설명은 아래에!)

- Runner
Gitbub Action Runner 어플리케이션이 설치된 머신으로, Workflow가 실행될 인스턴스

## 1. 액션시작하기
 set up a workflow yourself 를 클릭하여 셋팅을 시작한다
![image](https://user-images.githubusercontent.com/107670953/189486648-e94d926b-c230-4888-bd39-559f14771d01.png)

아래 이미지는 다음화면
![image](https://user-images.githubusercontent.com/107670953/189486728-d53788fa-374e-42ee-9378-2e887baa9365.png)
커밋 뉴 파일을 클릭한다

## 2. 폴더를 만들어보자
  vs code상 다음과 같은 위치에 .github/workflows를 생성한 후 .yml 야매룽파일을 생성하거나 1번에서 셋팅옵션을 git pull을 통해 받아온다
![image](https://user-images.githubusercontent.com/107670953/189486535-e29ae090-50c5-464a-907e-f08c87973a55.png)

## 3. .env 파일에 있는 환경변수를 셋팅하자
  new repository secret을 클릭한다
![image](https://user-images.githubusercontent.com/107670953/189486829-79ced7ce-8631-4aab-817a-882d331b61b6.png)

만약 .env 파일에 JWT_SECRET=jwtsecret 같은 변수가 있다면 
![image](https://user-images.githubusercontent.com/107670953/189486867-d3333317-f61a-4335-8c7d-162a3f6bdcd3.png)

위와 같은 방법으로 .env파일의 환경변수를 모두 셋팅해준다

## 4. yml (야매룽) 파일을 셋팅해보자
![image](https://user-images.githubusercontent.com/107670953/189486944-4acc6a34-13e4-4f20-8da1-0ab0547bcc5f.png)

3번째줄의 name: 은 깃헙액션에서 사용할 이름이다 (편하게 지으면 ok)

6~ 11 줄은 어떠한 사건이 발생했을 때 이 workflow가 작동하게 한다 
나는 dev라는 branch에 push가 발생했을때 작동하게 셋팅을 하였다
paths 나 paths-ignore를 통하여 특정 파일이 변경되었을때 작동하도록 할 수도 있다

``` javascript
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.16.0]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm -v

      # Runs a set of commands using the runners shell
      - name: create env
        run: |
          pwd
          touch .env
          echo DB_ID=${{ secrets.DB_ID }} >> .env
          echo DB_PW=${{ secrets.DB_PW }} >> .env
          echo DB_HOST=${{ secrets.DB_HOST }} >> .env
          echo DB=${{ secrets.DB }} >> .env
          echo GIT_ID=${{ secrets.GIT_ID }} >> .env
          echo GIT_SECRET=${{ secrets.GIT_SECRET }} >> .env
          echo GIT_URL=${{ secrets.GIT_URL }} >> .env
          echo REDIS_HOST=${{ secrets.REDIS_HOST }} >> .env
          echo REDIS_PORT=${{ secrets.REDIS_PORT }} >> .env
          echo REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }} >> .env
          echo COOKIE_SECRET=${{ secrets.COOKIE_SECRET }} >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env

      - name: build server files
        working-directory: ./
        run: |
          npm i nodemon
          npm run dev

```
runs on 은 가장 최신 우분투를 사용한다라는 뜻

strategy 는 테스트나 배포환경에서 설정한 노드버전을 사용한다 라는 뜻 (이 부분은 [10.x, 12.x, 14.x] 처럼 여러환경에서 테스트할 수도 있음)

steps 는 job의 행동을 뜻함
- uses : 그 스텝에서 사용할 액션을 말하며 깃헙 마켓플레이스에 올라온 액션을 사용할수도 있음
- name : step의 이름을 의미함
- run : 내가 사용할 명령을 뜻함
``` javascript
name: Run a one-line script
        run: npm -v
```
이곳에서는 npm -v 를 통하여 npm버전을 확인하는 작업을 한다

name : create env 를 통하여 내가 설정한 환경변수(위에서 깃헙액션에 등록한 환경변수) 를 읽어서 .env 파일을 생성한다

그후 npm run dev를 위한 nodemon을 설치한다 ( nodemon 없이 실행해보니까 module error가 발생했었다)

이러면 db connect가 나타나며 작동이 되는것을 확인했습니다

일단 여기까지 진행이 되었는데 여기서 다음으로 넘어가지 않는 문제가 있다 이는 aws codedeploy를 통한 배포를 진행하며 해결할 예정입니다.

**Comment by kpzzy** [comment]
# aws Code Deploy
less /var/log/aws/codedeploy-agent/codedeploy-agent.log

## 준비물 
1. aws ec2 인스턴스 1대
2. s3 bucket 1개
3. code deploy 애플리케이션, 그룹 설정

## 파일 구조 
![image](https://user-images.githubusercontent.com/107670953/189520832-187f5897-c16f-4b9e-84d7-68a8bd59c2ee.png)

## AWS S3 버킷을 생성합니다
AWS S3 > 버킷 만들기 클릭
![image](https://user-images.githubusercontent.com/107670953/189520903-67f286e3-4fa5-4f87-939f-b07e1c4f47ed.png)
![image](https://user-images.githubusercontent.com/107670953/189520913-caafc892-09e4-4413-b722-3d9b83eb54cb.png)
버킷이름을 편하게 입력해주신후 버킷생성을 클릭합니다(본인 필요에 의하여 설정하시면 됩니다)
저는 버킷이름을 제외한 다른 설정은 만지지 않았습니다

## EC2 IAM 설정
AWS IAM 에 들어오신 후 역할클릭 이후 역할 만들기를 클릭합니다
![image](https://user-images.githubusercontent.com/107670953/189521526-e4c64c99-ee6a-408f-86f7-68c0a385910b.png)


![image](https://user-images.githubusercontent.com/107670953/189521558-c763d411-85c3-44d6-bddf-c27be64c7924.png)
EC2 클릭 후 다음을 누릅니다

![image](https://user-images.githubusercontent.com/107670953/189521587-13322cde-e005-4706-98c6-9a8cf8c54daf.png)
우리는 AWS S3 와 AWS Code Deploy를 사용할 예정이기 때문에 

AmazonS3FullAccess
AWSCodeDeployFullAccess

이 두개를 검색하신 후 체크를 해 줍니다

![image](https://user-images.githubusercontent.com/107670953/189521644-e6b75c3d-dfb3-4fc6-a67a-c67819142cc6.png)

그 후 다음을 누른 후

![image](https://user-images.githubusercontent.com/107670953/189521674-3c970022-2566-4578-8700-bf716ef4ad5a.png)

그 다음 역할 생성을 눌러주시면 됩니다

## EC2 설정
![image](https://user-images.githubusercontent.com/107670953/189521993-10b3b416-2b95-46f7-8aa3-d331f636a488.png)

그 후 EC2 인스턴스에 오신 후 인스턴스 우클릭 >> 보안 >> IAM역할수정에 들어갑니다

![image](https://user-images.githubusercontent.com/107670953/189522130-60d88074-299d-400a-b410-3582ddab33ba.png)
그러면 다음과 같은 화면이 나오는데 여기서 위에서 생성하신 역할을 클릭한 후 IAM 역할 업데이트를 클릭합니다

(이후 인스턴스 우클릭 후 인스턴스 재부팅을 누르라는 말도 있던데 저는 생략하였습니다 재부팅을 하셔도 무관합니다)

## 잊지말기) 인스턴스의 Name 을 반드시 설정하셔야합니다

## CodeDeploy IAM 설정하기
AWS IAM에 오신 후 역할 만들기를 다시 한번 눌러줍니다

![image](https://user-images.githubusercontent.com/107670953/189522296-e0da2d34-ee76-44b7-ab08-ee14869b6043.png)

![image](https://user-images.githubusercontent.com/107670953/189522343-8d3395a6-7562-4ebe-9a01-f360916a5352.png)

그 다음 위 사진처럼 다른 AWS 서비스의 사용사례에 CodeDeploy 검색 후 사진처럼 설정을 하신 후 다음을 눌러줍니다

![image](https://user-images.githubusercontent.com/107670953/189522430-911ee2e6-0af1-4af3-833c-f7dad63fdd8b.png)

그러면은 다음과 같은 화면이 나오는데 다음을 누르신 후 

![image](https://user-images.githubusercontent.com/107670953/189522453-962cd042-fda6-4464-98d1-1422177f7356.png)

역할 이름을 지정하신 후 역할 생성을 클릭합니다

## 코드 디플로이 설정하기
AWS Code Deploy 에 오신 후 

![image](https://user-images.githubusercontent.com/107670953/189522535-0d444ebd-87e4-46a0-bca3-7a22008fa25f.png)

애플리케이션 생성을 클릭하여 줍니다

![image](https://user-images.githubusercontent.com/107670953/189522594-6cc8766c-51e3-4423-b6b0-852ffa153a73.png)


그 후 애플리케이션 이름을 설정하신 후 플랫폼은 EC2/온프레미스를 누르신 후 애플리케이션 생성을 클릭해주세요

![image](https://user-images.githubusercontent.com/107670953/189522621-0ebe33f5-29eb-4991-855c-b181ab6a0a86.png)

잘 생성이 되었다면 위와 같은 화면이 나올텐데 여기서 애플리케이션이름 (sd-cd)를 눌러주면 다음과 같은 화면이 나옵니다

![image](https://user-images.githubusercontent.com/107670953/189522643-3ab45544-6cce-485c-91cb-7f5bd6520d1d.png)

여기서 배포 그룹 생성을 눌러주세요

![image](https://user-images.githubusercontent.com/107670953/189522676-cbbdc2c5-1d04-47b9-aef1-27f2a631e65b.png)

그러면 다음과 같은 화면으로 넘어오는데 배포그룹 이름입력 후 서비스 역할은 code deploy IAM 설정때 했던 역할을 입력합니다

![image](https://user-images.githubusercontent.com/107670953/189522726-3102fa9c-01c5-4162-b253-55027cfa1c7f.png)

이후 환경 구성에서 Amazon EC2 인스턴스를 클릭하면 태그그룹1에 키 Name 값 EC2 인스턴스 이름이 나옵니다 (나오지 않는다면 EC2 인스턴스의 이름을 설정했는지 확인해주세요)

![image](https://user-images.githubusercontent.com/107670953/189522776-00f0a9f0-96ec-4fd5-875c-2597c155c7a9.png)

이후 배포설정을 다음과 같이 설정한 후 로드밸런싱 활성화를 해제한 후 배포그룹 생성을 눌러줍니다

## IAM 사용자를 추가해보자
![image](https://user-images.githubusercontent.com/107670953/189522903-326af92f-0f03-46f3-ac48-05d05d1ed6b9.png)

IAM에 오셔서 액세스관리 - 사용자 - 사용자 추가버튼을 눌러주세요

![image](https://user-images.githubusercontent.com/107670953/189522938-900ce07b-79a4-46b2-a374-fdf38de85d81.png)

위 이미지처럼 지정 후 다음을 눌러줍니다

![image](https://user-images.githubusercontent.com/107670953/189522970-a9bd73b8-0fda-4afb-bbdf-53389753a636.png)

그후 기존 정책 직접 연결에서 정책필터에 다음 2개의 정책을 검색후 체크해주세요

AmazonS3FullAccess
AWSCodeDeployFullAccess

위 2개의 정책을 설정하셨다면 다음 버튼을 눌러주세요 

그 후 다음과 같은 이미지가 나올때까지 그냥 다음을 눌러주세요

![image](https://user-images.githubusercontent.com/107670953/189523021-0c5dcc99-4a6e-4c53-b208-c51f406bbd31.png)

## 중요) 여기서 액세스키 ID와 비밀 액세스 키는 메모장에 저장해두시거나 .CSV 다운로드해주세요 (저는 메모장에 저장했습니다)

그 후 깃허브 액션 시크릿에 추가해 주도록 합니다

![image](https://user-images.githubusercontent.com/107670953/189523084-298950c2-59a3-4051-8aca-c6353adc59c6.png)

**Comment by kpzzy** [comment]
# 3부 깃허브 액션으로 CI/CD 성공시키기
## EC2 CodeDeploy Agent 를 설치해보자

(저는 우분투 환경에서 진행하였는데 우분투가 처음이라면 npm이나 node , pm2 등을 설치 후 진행해주세요)

AWS CodeDeploy를 사용하기 위해 EC2 인스턴스의 ssh 에 접속하여 CodeDeploy Agent 를 설치합니다 

step1. awscli 를 설치합니다
``` javascript
$ sudo apt update
$ sudo apt install awscli
```
step2. 
``` javascript
$ sudo aws configure
AWS Access Key ID : IAM 사용자 만드셨을때 저장하신 Access Key를 입력해주세요
AWS Secret Access KEy : IAM 사용자 만드셨을때 저장하신 Secret Access Key를 입력해주세요
Default region name : ap-northeast-2 (인스턴스 확인후 진행해주세요)
Default output format : json
```
``` javascript
$ wget https://aws-codedeploy-ap-northeast-2.s3.amazonaws.com/latest/install
// 가장 최신버전의 코드 디플로이 에이전트를 설치합니다
$ chmod +x ./install
// install 파일에 권한을 추가합니다
```
``` javascript
$ sudo apt-get install ruby
// 진행을 도와줄 루비를 설치합니다
$ sudo ./install auto
// 루비가 코드 디플로이 에이전트를 설치해줍니다
$ sudo service codedeploy-agent status  
// 설치를 확인합니다
```
![image](https://user-images.githubusercontent.com/107670953/189524502-c7211ed5-040f-450f-9107-3574bfa6db29.png)
status 입력했을때 위와같다면 정상설치가 되었습니다

ec2 인스턴스가 켜졌을때 코드디플로이 에이전트가 자동재시작을 하기 위해서 다음과 같은 shell script를 작성한다
``` javascript
$ sudo vim /etc/init.d/codedeploy-startup.sh
// i 눌르고 
#!/bin
sudo service codedeploy-agent restart
// esc 누르고 :wq로 저장 나가기

// 이후
$ sudo chmod +x /etc/init.d/codedeploy-startup.sh
// 로 실행권한 부여
```
## appspec.yml 파일을 생성합니다

![image](https://user-images.githubusercontent.com/107670953/189527427-ed100085-444d-4990-bb63-b354cc71cb9a.png)
appspec.yml 파일은 코드디플로이가 배포를 관리할 애플리케이션 파일입니다

``` javascript
files:
    - sourcd: /
    - destination: /home/ubuntu/QBChaining-BE    << 이부분은 본인의 우분투상 폴더위치를 지정해주시면 됩니다
    -  overwrite: yes 덮어쓰기 기능입니다
    - file_exists_behavior: OVERWRITE (이 부분은 덮어쓰기 기능이 작동하지 않아 검색해본결과 추가하였습니다)

hooks:
    AfterInstall:
    // 설치 후 작동할 후크(트리거) 부분입니다
    - location : scripts/after-deploy.sh    << 스크립트 폴더안의 애프터 디플로이.SH 파일을 실행시킵니다
```

코드디플로이가 EC2 인스턴스에 파일들을 옮긴 후 hooks를 통하여 다음작업을 지정할수 있습니다

## scripts폴더안에 after-deploy.sh 를 생성해보자
``` javascript
#!/bin/bash
REPOSITORY=/home/ubuntu/QBChaining-BE

cd $REPOSITORY

sudo npm ci

sudo pm2 restart ./src/app.js
```
REPOSITORY는 폴더가 저장된 경로를 뜻합니다

cd $REPOSITORY를 통하여 폴더 위치로 이동한 후

sudo 로 관리자 권한으로 npm ci를 실행합니다

이후 pm2가 실행되어있었다면 

pm2 restart로 (처음키신다면 pm2 start로 켜줍니다) 본인의 파일을 실행시켜줍니다 (저는 app.js로 사용하였습니다)

## 이제 deploy.yml 파일을 수정해보자
파일 전체 내용입니다
![image](https://user-images.githubusercontent.com/107670953/189528095-dc90443b-ff07-411f-aa7f-464401c224f9.png)
![image](https://user-images.githubusercontent.com/107670953/189528114-97bee8cd-56c2-4ab2-a75f-03fdb4aa6710.png)
![image](https://user-images.githubusercontent.com/107670953/189528141-52636660-5bd6-4db7-b757-6f7f99f36f3c.png)

``` javascript
      - run: npm install
      - run: npm run build --if-present

      - name: zip file
        run: zip -r hous.zip .github/workflows ./package.json ./package-lock.json ./src ./node_modules ./appspec.yml ./scripts
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://kpzzy-build/action-test/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name sd-cd
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name baepo
          --s3-location bucket=kpzzy-build,bundleType=zip,key=action-test/hous.zip
```
추가된 내용을 살펴보겠습니다

```
      - run: npm install <<< npm install로 라이브러리를 설치합니다
      - run: npm run build --if-present <<< package.json 의 script 설정한 build를 실행합니다 
```
```
"scripts": {
    "start": "cross-env NODE_ENV=production PORT=80 pm2 start ./src/app.js -i 0",
    "dev": "nodemon ./src/app.js",
    "test": "jest",
    "build": ""
  },
```
package.json 내부의 스크립트 입니다

```
 - name: zip file
        run: zip -r hous.zip .github/workflows ./package.json ./package-lock.json ./src ./node_modules ./appspec.yml ./scripts
```
vs code상의 폴더들을 압축합니다

왜? why?? 혹시 git push 하실때 gitignore를 사용하지 않고 노드 모듈과 패키지 락.json을 푸쉬 해보신적이 있으신가요 **엄!청!** 오래걸립니다

```
      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
```
aws-action 을 사용합니다
환경변수에 등록해둔 ACCESS KEY와 SECRET ACCESS KEY 를 등록한 후 aws-region 도 등록하여줍니다

```
      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./hous.zip s3://kpzzy-build/action-test/

```
aws s3에 압축한 hous.zip 파일을 옮깁니다 자세히 보겠습니다

./hous.zip s3://kpzzy-build/action-test/   <<< ./hous.zip   은 압축한 파일을 뜻합니다 
s3://당신의 버킷네임을 등록해주세요/action-test라는 폴더를 생성하고 그 안에 압축파일을 넣습니다/

```
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name sd-cd
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name baepo
          --s3-location bucket=kpzzy-build,bundleType=zip,key=action-test/hous.zip
```
코드디플로이를 실행합니다 한줄씩 보겠습니다

```
aws deploy create-deployment
```
AWS code deploy가 실행되고 배포 내역에 추가됩니다

```
--application-name sd-cd    << 설정한 애플리케이션 이름을 입력합니다
```

```
--deployment-config-name CodeDeployDefault.AllAtOnce  << 이 부분은 코드디플로이 설정상태를 입력해줍니다
```

```
--deployment-group-name baepo   << 배포그룹 이름을 입력합니다
```

```
--s3-location bucket=kpzzy-build,bundleType=zip,key=action-test/hous.zip  
// 풀어서 보겠습니다 s3-location bucket= 버켓명을 입력합니다   bundleType=압축명을입력합니다 key=s3버켓폴더명과 그 내부에 저장된 .zip 파일을 입력합니다
```

이제 deploy.yml 파일에서 dev 브랜치에 push 했을때 깃허브 액션이 작동하기 때문에 git push origin dev를 한다면 성공합니다

![image](https://user-images.githubusercontent.com/107670953/189535127-437ed2ea-efcf-4130-a38f-fb37d6ec353f.png)


여러분 저는 75번의 도전끝에 성공했습니다

이 글을 보신 여러분은 1번의 시도로 성공하시기를 기원하며 작성했습니다

다들 화이팅입니다

## s3버켓을 사용하지 않고 code deploy를 하고싶다면??
https://github.com/codeing999/CLIPs-backend/issues/59

여기를 참고하셔도 좋습니다

**Comment by kpzzy** [comment]
코드디플로이상태의 로그를 확인하고 싶다면 우분투에 
less /var/log/aws/codedeploy-agent/codedeploy-agent.log 입력하면 보실수 있습니다

**Comment by codeing999** [comment]
따봉 누르고 갑니다
